[2023-09-18 22:13:43,851] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,853] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,853] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,861] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,861] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,861] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,870] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,870] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,876] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,883] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,876] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,876] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,887] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,892] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,901] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,901] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,905] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,905] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,905] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,909] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,909] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,909] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,909] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,909] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,918] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:13:43,919] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:13:43,920] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:13:43] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:15:17,037] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:15:17] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:15:17,699] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:15:17] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:15:58,363] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:15:58] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:15:59,874] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:15:59] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:16:07,128] WARNING add_cliente() L42   Adicionando cliente de nome: 'nnnn' - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L42  
[2023-09-18 22:16:07,151] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:16:07] "POST /cadastrar_cliente HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:16:50,116] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:16:50] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:19:26,739] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:19:26] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:20:32,000] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:20:32] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:23:11,026] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:23:11] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:25:19,539] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:25:19] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:25:33,480] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:25:33] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:25:43,305] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:25:43] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:25:50,097] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:25:50] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:27:52,342] INFO _log() L187  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:27:52,342] INFO _log() L187  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:27:53,410] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:27:53] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
