[2023-09-18 22:12:14,889] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,889] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,889] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,889] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,889] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,889] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,905] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,905] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,905] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,905] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,915] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,915] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,915] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,915] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,915] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,921] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,921] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,930] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,930] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,933] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,933] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,940] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,942] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,947] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,948] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,948] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,955] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,957] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,958] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,958] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,958] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,958] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,973] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,975] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,975] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,975] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,975] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,975] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,983] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,985] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,991] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,991] WARNING del_cliente() L128  Erro ao deletar cliente #'undefined', Cliente não encontrado na base :/ - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\app.py L128 
[2023-09-18 22:12:14,991] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
[2023-09-18 22:12:14,991] INFO _log() L187  127.0.0.1 - - [18/Sep/2023 22:12:14] "[33mDELETE /deletar_cliente?nome=undefined HTTP/1.1[0m" 404 - - call_trace=C:\Users\leand\Desktop\sprint 1\mvp_app_api\env\Lib\site-packages\werkzeug\_internal.py L187 
